---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks1
  namespace: torus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks1
  template:
    metadata:
      labels:
        app: eks1
    spec:
      containers:
      - name: hello-kubernetes
        image: erickyataco/hello-kubernetes:1.8.2
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: Hello Kubernetes! - EKS v1
