---
apiVersion: v1
kind: Service
metadata:
  name: eks1
  namespace: torus
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-security-groups: eksNodeSecurityGroup
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: eks1
