---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team1
  namespace: team1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team1
  template:
    metadata:
      labels:
        app: team1
    spec:
      containers:
      - name: hello-kubernetes
        image: erickyataco/hello-kubernetes:1.8.2
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: Hello Kubernetes! - team1
